### ISSUE TITLE
Whitelist is not set properly unless aemm-plugin-navto is installed.

### ISSUE THREAD

**Issue by huacyang** [adobe-marketing-cloud-mobile/aemmobile#28]
**Issue:** Clicking on an anchor tag (i.e. #cqm_device) will open the current page in an IAB, scrolled down to the correct position, and with the message: "Content Not Found".

**Expect:** Clicking on an anchor tag to scroll to the correct position within the same page. This works fine in the preflight app.

#### Reference

A list of anchor tags, i.e. `<li><a href="#cqm_device">CQM Device</a></li>`
<img width="487" alt="anchor-tag-list" src="https://cloud.githubusercontent.com/assets/2553616/16975600/27dd705c-4e16-11e6-82c7-dd1b61dfdf13.png">

Opening same page in the IAB, scrolled down to the correct position, with error message
<img width="487" alt="anchor-tag-open" src="https://cloud.githubusercontent.com/assets/2553616/16975601/27e732ea-4e16-11e6-8869-ba1263b941a4.png">

**Comment by adzellman** [comment]
@huacyang We have had other similar reports of this behavior. We believe we've found a workaround, which is to install aemm-plugin-navto. This is due to whitelist configurations that are built into the navto plugin. If aemm-plugin-navto is not included, then the hrefs (including anchors) in the page are not in the whitelist and will cause an external browser to launch instead of navigating within the page.
